

def printHelp() {
  log.info"""
  Usage:
    nextflow run ncov-nf/nextstrain -profile (singularity,docker,conda) -mode (refine_iterations, random_subsets_no_align, random_subsets, lineages)

  Description:
    Parallelize a series of Nextstrain builds using random data subsets, either based on random sampling of a metadata file, or by Pango lineage assignment.
    Can also be used for parallel testing of TreeTime refine clock thresholds

  Nextflow arguments (single DASH):
    -profile                  Allowed values: singularity, docker, conda
  
  Mandatory workflow arguments:
      --mode 		      Defines the type of Nextstrain build to construct

  Other Workflow parameters:
      --subset_number         	If creating a random subset, specify how many sequences to include
                             
      --clockfilteriqd        	Specify the clock filter threshold for treeTime during augur refine

      --alignment_ref         	Path to the alignment reference that is compatible with mafft and augur align

      --metadata              	Path to a PHO-specific metadata sheet that is generated from the Access database, containing all metadta fields required for a PHO public build
    
      --output_dir            	Specify a general output directory. Each build will get a unique sub-diretory in this location with all intermediate pipeline files

      --colortsv 	      	Path to the colors tsv that is requied for auspice to show regional information on a map

      --config 		      	Path to the general configuration JSON required to export a Nextstrain build for import into augur. This JSON is PHO-specific

      --latlong		      	Path to the TSV file containing map coordinates for Ontario Health Regions. 

      --clades		      	Path to a TSV file provided by Nextstrain to annotate differenT COVID-19 clades based on defining mutation sites
       
      --threads 	      	Number of threads that each individual instance of augur align or augur tree can access

      --cleanup 	      	Clean the working directory after completion of the nextflow run

      --start_iteration	      	Starting placeholder integer for random subsets. Used to provide an identifier to a specific random build. Must be smaller than --stop_iteration.

      --stop_iteration        	Terminating placeholder integer for random subsets. Used to provide an identifier to a specific random build. Must be larger than --start_iteration.

      --clock                 	If using refine_terations mode, test all augur refine clock filters from 1 to this integer. 

      --lineages	      	For the lineages mode, create a complete build for each Pango lineage in the list. Example: ["P.1", "B.1.1.7", "B.1.617.2"]

      --lineage_report	      	Path to a lineage report generated by pangolin for use in the lineages mode

      --master_fasta	      	Path to the master (unaligned) multi-FASTA of PHO sequences to create sub-sampled builds from

      --nextalign             	Path to a master multi-alignment file generated by Nextclade. Used for the random_subsets_no_align mode

      --cache                 	If set as '', specify the cache directory in the work directory

      --tracedir              	Path specifying the output for traces such as the log, execution trace, pipline dag, and timeline report

      --refineseed	      	Integer specifying a random seed for augur refine. Used to reproduce refine analyses in TreeTime

      --clean_dir	      	If selected as true, clean the individual build directories to remove all files except the sub-sampled metadata sheet and augur refine clock output log

  """.stripIndent()
}
